name: Multi Semantic Release
description: Action that handles multi package semantic release from one repo (monorepo)

runs:
  using: node16
  main: main.js

branding:
  icon: cloud-lightning
  color: gray-dark

inputs:
  github-token:
    description: token to use to do the release
    required: true
  dry-run:
    description: whether to do a dry run
    required: false
    default: "false"

outputs:
  something-was-released:
    description: whether any packages were released (boolean)
  new-versions:
    description: list of projects and their new versions that will be (if dry-run) or were released
  package-was-released:
    description: JSON object containing boolean value for each package (whether it was released) keyed by package name
